app/models/chain-store/chain-store.ts

🐛 Fix wallet caching issues

---

app/screens/staking-unbonding-delegation-signing-screen/staking-unbonding-delegation-signing-screen.tsx

🐛 Resolve balance out-sync after undelegating

---

app/utils/firebase.ts

🐛 Fix logout crash

---

app/models/staking-delegation-store/staking-delegation-store.ts
app/models/staking-rewards-withdraw-store/staking-rewards-withdraw-store.ts
app/models/staking-unbonding-delegation-store/staking-unbonding-delegation-store.ts
app/models/transfer-store/transfer-store.ts
app/models/tx-store/tx-store.ts

Please review with hide whitespace changes

Improve TxStoreModel & its dependants references

---

app/screens/content-view-screen/content-view-screen.tsx
app/screens/likerland-oauth-screen/likerland-oauth-screen.tsx
app/services/api/api-config.ts

🎨 Append user agent of device instead of override

---

app/screens/wallet-dashboard-screen/wallet-dashboard-screen.tsx

Should be string instead of whole object

🐛 Fix validator payload in analytics

---

app/i18n/en.json
app/i18n/zh-Hant-HK.json
app/models/chain-store/chain-store.ts
app/models/validator/validator.ts
app/screens/validator-screen/validator-screen.tsx
app/services/cosmos/cosmos.ts
app/services/cosmos/cosmos.utils.ts

Add pull to refresh in validator screen

---

app/i18n/en.json
app/i18n/zh-Hant-HK.json
app/screens/settings-screen/settings-screen.tsx

📄 Add open source license link in settings screen

---

README.md

Should solve the GPL conflict with apple app store 
https://github.com/likecoin/likecoin-app/commit/caad3a77512ea8ef894292f8dd99131df4a01393#commitcomment-37208591
thanks @denkeni for the information

📄 Update README.md & additional license for app store

---

.github/workflows/production_build.yaml
.github/workflows/release.yaml
android/fastlane/Fastfile
ios/fastlane/Fastfile

release tag must strictly be in the format v0.15.1-172(-2) where v(version name)-(build)(?-(extra))

👷 Add android apk release build and ios dsyms on github release create 

---

app/i18n/en.json
app/i18n/zh-Hant-HK.json
app/models/user-store/user-store.ts
app/services/branch-io/branch-io.ts

en is not translated on purpose as requested by @edmondyu

✨ Add og for app referral link

---

app/i18n/zh-Hant-TW.json

這個繁體中文(台灣)是用原有的香港譯版+英文譯版參考編輯的。
> 雖然說這是i18n，但還是想要建立這個pull
大部分的差別是在用詞的部分、句子的表達。例如: 二維碼->QR 碼；辨識->識別；列表->清單 ,.etc
- 錯字修正
由於我不了解程式碼的運作，因此我可能無法順帶 pull 像是 "繁體中文(台灣)"之類的操作介面按鈕。😥
---
其實港版跟台版差異不大，只是擔心說港人使用時某些詞、字是不通用的。所以說如果審核後發現台灣的詞是跟港通用的，或許可以合併？(變成zh-hk)
> 英文不好，所以就寫中文了。
My English is very poor, if you can't understand Chinese please use the translator, sorry for causing your trouble.

Create zh-Hant-TW i18n

---

app/models/authcore-store/authcore-store.ts
app/models/environment.ts
app/models/root-store/setup-root-store.ts
app/models/user-store/user-store.ts
app/screens/auth-loading-screen/auth-loading-screen.tsx
app/services/authcore/authcore.ts
app/utils/analytics.ts

Pinging authcore/secretd is a long process, this PR attempt to make it parallel with other async loading process to improve resume speed

⚡️ Make login resume process async to improve load speed

---

app/components/signing-view/signing-view.props.ts
app/components/signing-view/signing-view.style.ts
app/components/signing-view/signing-view.tsx
app/i18n/en.json
app/i18n/zh-Hant-HK.json
app/models/tx-store/tx-store.ts
app/navigation/transfer-navigator.ts
app/screens/transfer-memo-input-screen/index.ts
app/screens/transfer-memo-input-screen/transfer-memo-input-screen.tsx
app/screens/transfer-signing-screen/transfer-signing-screen.tsx
app/screens/transfer-target-input-screen/transfer-target-input-screen.tsx

✨ Add transfer memo input

---

android/app/build.gradle
android/app/src/main/java/com/oice/MainApplication.java

We support android min api 21, which means we are not bounded to okhttp3
need to check how this affect apk size though

➕ Upgrade okhttp to try to use tls1.3

---

app/screens/settings-screen/settings-screen-statistics-panel.style.ts
app/screens/settings-screen/settings-screen-statistics-panel.tsx
app/screens/settings-screen/settings-screen-user-info-panel.style.ts
app/screens/settings-screen/settings-screen-user-info-panel.tsx
app/screens/settings-screen/settings-screen-wallet-panel.style.ts
app/screens/settings-screen/settings-screen-wallet-panel.tsx
app/screens/settings-screen/settings-screen.style.ts
app/screens/settings-screen/settings-screen.tsx

Update wallet panel and refactor settings screen

---

app/models/reader-store/reader-store.ts
app/models/root-store/root-store.ts
app/models/root-store/setup-root-store.ts
app/models/user-store/user-store.ts
app/screens/auth-loading-screen/auth-loading-screen.tsx
app/screens/likerland-oauth-screen/likerland-oauth-screen.tsx
app/services/branch-io/branch-io.ts

Also refactored existing auto follow for post login

✨ Handle referral deeplink to add followed user

---

app/models/authcore-store/authcore-store.ts
app/screens/sign-in-screen/sign-in-screen.tsx
app/services/authcore/authcore.ts
package.json
yarn.lock

Still waiting for react-native-authcore update
Resolve #221

♻️ Authcore signin widget changes

---

app/i18n/translations/en.json
app/i18n/translations/zh-Hans-CN.json
app/i18n/translations/zh-Hant-HK.json
app/i18n/translations/zh-Hant-TW.json
app/models/authcore-store/authcore-store.ts
app/navigation/settings-navigator.ts
app/screens/profile-settings-screen/index.ts
app/screens/profile-settings-screen/profile-settings-screen.tsx
app/screens/settings-screen/settings-screen.tsx

✨ Add Authcore profile settings screen

---

ios/LikeCoinApp/Info.plist

ref: https://medium.com/@rizwanm/tracker-prevention-for-wkwebview-c566f0819812

👽 Add iOS setting to allow iOS14 user to disable ITP

---

.github/workflows/production_build.yaml
.github/workflows/release.yaml

Update secret in repo with base64 encoded version

👷 Use base64 to encode sentry.properties

---

.github/workflows/production_build.yaml
.github/workflows/release.yaml
ios/fastlane/Fastfile

Added the following secret into repo
APPLE_CONNECT_API_ISSUER_ID
APPLE_CONNECT_API_KEY_ID
APPLE_CONNECT_API_KEY_SECRET

🔧 Add apple connect api key in ci and fastlane

---

app/utils/number.ts

💩 Fix 0.000 like amount

---

app/components/header-tab-container-view/header-tab-container-view.tsx
app/components/validator-list-item/validator-list-item.props.ts
app/components/validator-list-item/validator-list-item.style.ts
app/components/validator-list-item/validator-list-item.tsx
app/components/validator-list/validator-list.tsx
app/screens/validator-list-screen/validator-list-screen.tsx
test/__snapshots__/storyshots.test.ts.snap

In addition, shows index for validator list item

Fix validators list on Android

---

app/components/content-list-item/content-list-item-action-sheet.super-like.tsx
app/components/content-list/content-list.super-like.tsx
app/i18n/translations/en.json
app/i18n/translations/zh-Hans-CN.json
app/i18n/translations/zh-Hant-HK.json
app/i18n/translations/zh-Hant-TW.json
app/models/my-super-likes-store/index.ts
app/models/my-super-likes-store/my-super-likes-store.test.ts
app/models/my-super-likes-store/my-super-likes-store.ts
app/models/root-store/root-store.ts
app/models/super-like-following-store/index.ts
app/models/super-like-following-store/super-like-following-store.test.ts
app/screens/my-super-likes-screen/index.ts
app/screens/my-super-likes-screen/my-super-likes-screen.props.ts
app/screens/my-super-likes-screen/my-super-likes-screen.tsx
app/screens/reader-screen/reader-screen.tsx
app/screens/settings-screen/settings-screen.tsx
app/screens/super-like-following-screen/index.ts
app/screens/super-like-global-feed-screen/super-like-global-feed-screen.tsx
app/services/api/likerland-api.ts

✨ Change following feed to self feed

---

app/screens/referrer-input-screen/referrer-input-screen.tsx

https://github.com/likecoin/likecoin-api-public/pull/378

🔧 Lower LikerId regex to min 5 char

---

app/components/button/button.presets.ts
app/i18n/translations/en.json
app/i18n/translations/zh-Hans-CN.json
app/i18n/translations/zh-Hant-HK.json
app/i18n/translations/zh-Hant-TW.json
app/models/chain-store/chain-store.ts
app/models/user-store/user-store.ts
app/navigation/settings-navigator.ts
app/screens/account-delete-screen/account-delete-screen.tsx
app/screens/account-delete-screen/index.ts
app/screens/registration-screen/registration-screen.tsx
app/screens/settings-screen/settings-screen.tsx
app/services/api/likeco-api.ts

✨ Add account delete

---

app/i18n/translations/en.json
app/i18n/translations/zh-Hans-CN.json
app/i18n/translations/zh-Hant-HK.json
app/i18n/translations/zh-Hant-TW.json
app/models/authcore-store/authcore-store.ts
app/screens/seed-words-export-screen/seed-words-export-screen.tsx

- Users can skip password authentication if their Authcore account is without a password (most likely using OAuth)
- Prevent users from using the incorrect OAuth login method

🐛 [Seed Words Export] Fix QA issues

---

app/i18n/translations/zh-Hans-CN.json
app/i18n/translations/zh-Hant-HK.json
app/i18n/translations/zh-Hant-TW.json

✏️ Fix typo

---

app/i18n/translations/en.json
app/i18n/translations/zh-Hans-CN.json
app/i18n/translations/zh-Hant-HK.json
app/i18n/translations/zh-Hant-TW.json
app/navigation/app-navigator.tsx
app/navigation/settings-navigator.ts
app/screens/reader-screen/reader-screen.tsx
app/screens/settings-screen/settings-screen.tsx

🏗️ Move depub.space to settings

---

app/i18n/translations/en.json
app/i18n/translations/zh-Hant-HK.json
app/i18n/translations/zh-Hant-TW.json

"Listing" → "Browse the Bookstore" 
"My Dashboard" → "My Bookshelf"

💬 Update translations 

---

app/models/deep-link-handle-store/deep-link-handle-store.ts
app/services/branch-io/branch-io.ts

Haven't test but this change seems trivial for non-defer deep links

✨ Add simple wallet connect support for branch deeplink

---

.circleci/config.yml
.github/workflows/lint_build.yml
.github/workflows/production_build.yaml
.github/workflows/release.yaml
package.json

Needed for upgrading other libraries

⬆️ Upgrade node to 16

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/res/values/strings.xml
app/utils/analytics.ts
ios/LikeCoinApp.xcodeproj/project.pbxproj
ios/LikeCoinApp/AppDelegate.m
ios/LikeCoinApp/Info.plist
ios/Podfile.lock
ios/en.lproj/InfoPlist.strings
package.json
yarn.lock

Cannot initialize app for now, need investigation

🔥 Remove Facebook SDK

---

package.json
yarn.lock

Requires https://github.com/likecoin/react-native-share-extension/pull/3

🚨 Fix warning for React Native

---

app/services/reactotron/reactotron.ts
app/utils/storage/storage.test.ts
app/utils/storage/storage.ts
ios/Podfile.lock
package.json
storybook/storybook.tsx
test/mock-async-storage.ts
yarn.lock

⬆️ Upgrade react-native-async-storage to v1.18.2

---

app/screens/nft-reader-screen/nft-reader-screen.tsx

Requires https://github.com/likecoin/liker-land/pull/1288

[TAS-329] 👽 Update NFT tab URL paths

---

ios/LikeCoinApp.xcodeproj/project.pbxproj

Ref: https://developer.apple.com/forums/thread/730974

👽️ Fix Xcode 15 cycle error
